package rentapi.jpacar.domain;


public enum AccidentType {
    ACCELERATOR, BREAKPDAL, GEARSTICK, STEERINGWHEEL, AIRCONDITIONING, HEATER, SEATBELT,
    BREAKLIGHT, HEADLAMPS, INDICATORS, REARLAMPS, WINGMIRROR,
    BATTERY, BREAKS, ENGINE, EXHAUST, BONNET, BUMPER, TIRES, WHEEL, WINDOW,
}
